trigger:
  branches:
    include:
      - main

variables:
  imageName: knowledgecity-backend
  containerRegistry: youracrname.azurecr.io
  aksCluster: knowledgecity-aks
  aksNamespace: knowledgecity

stages:
  - stage: Build
    displayName: "Build and Push Docker Image"
    jobs:
      - template: templates/build-stage.yml

  - stage: SecurityScan
    displayName: "Run Trivy Scan"
    dependsOn: Build
    jobs:
      - template: templates/security-scan.yml

  - stage: Deploy
    displayName: "Deploy to AKS"
    dependsOn: SecurityScan
    jobs:
      - template: templates/deploy-stage.yml
