jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - task: Docker@2
        displayName: "Build Docker Image"
        inputs:
          command: build
          Dockerfile: backend/Dockerfile
          tags: |
            $(containerRegistry)/$(imageName):$(Build.BuildId)

      - task: Docker@2
        displayName: "Push Docker Image"
        inputs:
          command: push
          tags: |
            $(containerRegistry)/$(imageName):$(Build.BuildId)
