apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledgecity-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backendcntainer
          image: REPLACE_IMAGE_DEV
