apiVersion: v1
kind: Service
metadata:
  name: knowledgecity-service
  namespace: backend
spec:
  selector:
    app: knowledgecity-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
